-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:



-- Exercise 1: Count the number of trips in January 2023
SELECT COUNT(*) AS Num_Jan
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
WHERE data_file_month = 1

Row	Num_Jan
1	2463931

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023
SELECT SUM(total_amount) AS Total_revenue
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 

Row	Total_revenue
1	775931967.69


-- Exercise 3: Find the most popular pickup location

SELECT pickup_location_id, COUNT(pickup_location_id) AS Loc_num_trips
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
GROUP BY pickup_location_id
ORDER BY Loc_num_trips DESC
LIMIT 1

Row	pickup_location_id	Loc_num_trips
1	    132	                1743244


-- Exercise 4: Analyze the number of trips per hour of the day

SELECT
  EXTRACT(DAY FROM pickup_datetime) AS day_of_trip,
  EXTRACT(HOUR FROM pickup_datetime) AS hour_of_day,
  COUNT(*) as Num_of_trips
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
WHERE DATE(pickup_datetime) = DATE '2022-01-01'
GROUP BY day_of_trip, hour_of_day


-- Exercise 5: Calculate the average trip distance
SELECT ROUND(AVG(trip_distance), 2) AS avg_trip_dist
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 

Row	avg_trip_dist
1	6.08

-- Exercise 6: Find the longest trip by distance
SELECT vendor_id, trip_distance
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
ORDER BY trip_distance DESC 
LIMIT 1

Row	vendor_id	trip_distance
1	    2	      389678.46


-- Exercise 7: Calculate the total number of passengers by payment type
SELECT payment_type, SUM(passenger_count) as pass_number
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
WHERE payment_type != "0"
GROUP BY payment_type
ORDER BY payment_type

Row	payment_type	pass_number
1	    1	        38232144
2	    2       	10292210
3	    3	        210382
4	    4	        265749
4	    5	            6

-- Exercise 8: Find the most common drop-off location for trips paid by credit card
SELECT dropoff_location_id, COUNT(*) as num_drop_off
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
WHERE payment_type = "1"
GROUP BY dropoff_location_id
ORDER BY num_drop_off DESC
LIMIT 1

Row	dropoff_location_id	num_drop_off
1	    236 	1236603

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT COUNT(*) as num_trips
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022` 
WHERE passenger_count > 4

Row	num_trips
1	1062813


-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance

WITH avg_dist AS (
  SELECT AVG(trip_distance) AS avg_trip_dist
  FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
)

SELECT ROUND(AVG(fare_amount), 2) as avg_fare
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`,
avg_dist
WHERE trip_distance > avg_dist.avg_trip_dist

Row	avg_fare
1	39.07